# Lab 5 Tasks

In this notebook we will analyse a dataset related to the London 2012 Olympics by using the Pandas library. In the dataset, each row represents a different country described by a number of features:

- *ISO:* Unique short ISO country code
- *Country*: Full country name
- *Gold*: Number of gold medals won by the country in 2012
- *Silver*: Number of silver medals won by the country in 2012
- *Bronze*: Number of bronze medals won by the country in 2012
- *Population*: 2011 population for the country, from the World Bank

## Task 1

Load the CSV file "olympics2012.csv" into a Pandas Data Frame, where each row is indexed by its ISO country code. Check the number of rows and the column names in the Data Frame.

In [3]:
import pandas as pd

df = pd.read_csv("olympics2012.csv")

Display the first 15 rows of the data.

In [4]:
df.head(15)

    ISO      Country  Gold  Silver  Bronze  Population
0   AFG  Afghanistan     0       0       1    35320445
1   ARG    Argentina     1       1       2    40764561
2   ARM      Armenia     0       1       2     3100236
3   AUS    Australia     7      16      12    22620600
4   AZE   Azerbaijan     2       2       6     9168000
5   BEL      Belgium     0       1       2    11008000
6   BGR     Bulgaria     0       1       1     7476000
7   BHR      Bahrain     0       0       1     1323535
8   BHS      Bahamas     1       0       0      347176
9   BLR      Belarus     3       5       5     9473000
10  BRA       Brazil     3       5       9   196655014
11  BWA     Botswana     0       1       0     2030738
12  CAN       Canada     1       5      12    34482779
13  CHE  Switzerland     2       2       0     7907000
14  CHN        China    38      27      22  1344130000

Show the top 10 countries with the highest number of gold medals at the 2012 Olympics.

In [5]:
df.sort_values("Gold", ascending=False).head(10)

    ISO             Country  Gold  Silver  Bronze  Population
81  USA       United States    46      29      29   311591917
14  CHN               China    38      27      22  1344130000
30  GBR       Great Britain    29      17      19    60924000
66  RUS  Russian Federation    24      25      33   141930000
47  KOR         Korea, Rep.    13       8       7    49779000
28  FRA              France    11      11      12    65436552
19  DEU             Germany    11      19      14    81726000
42  ITA               Italy     8       9      11    60770000
37  HUN             Hungary     8       4       5     9971000
45  KAZ          Kazakhstan     7       1       5    16558459

## Task 2

Create a new column in the Data Frame called "Total" which indicates the total number of medals won by each country. Show the top 10 countries with the highest number of total medals.

In [6]:
df["Total"] = df["Gold"] + df["Silver"] + df["Bronze"]
df.sort_values("Total", ascending=False).head(10)

    ISO             Country  Gold  Silver  Bronze  Population  Total
81  USA       United States    46      29      29   311591917    104
14  CHN               China    38      27      22  1344130000     87
66  RUS  Russian Federation    24      25      33   141930000     82
30  GBR       Great Britain    29      17      19    60924000     65
19  DEU             Germany    11      19      14    81726000     44
44  JPN               Japan     7      14      17   127817277     38
3   AUS           Australia     7      16      12    22620600     35
28  FRA              France    11      11      12    65436552     34
42  ITA               Italy     8       9      11    60770000     28
47  KOR         Korea, Rep.    13       8       7    49779000     28

Display the subset of countries which:
1. Won 20 or more gold medals
2. Won 25 or more total medals
3. Won only bronze medals

In [7]:
df.loc[df["Gold"] >= 20]

    ISO             Country  Gold  Silver  Bronze  Population  Total
14  CHN               China    38      27      22  1344130000     87
30  GBR       Great Britain    29      17      19    60924000     65
66  RUS  Russian Federation    24      25      33   141930000     82
81  USA       United States    46      29      29   311591917    104

In [8]:
df.loc[df["Total"] >= 25].sort_values("Total", ascending=False)

    ISO             Country  Gold  Silver  Bronze  Population  Total
81  USA       United States    46      29      29   311591917    104
14  CHN               China    38      27      22  1344130000     87
66  RUS  Russian Federation    24      25      33   141930000     82
30  GBR       Great Britain    29      17      19    60924000     65
19  DEU             Germany    11      19      14    81726000     44
44  JPN               Japan     7      14      17   127817277     38
3   AUS           Australia     7      16      12    22620600     35
28  FRA              France    11      11      12    65436552     34
42  ITA               Italy     8       9      11    60770000     28
47  KOR         Korea, Rep.    13       8       7    49779000     28

In [9]:
df.loc[(df["Bronze"] > 0) & (df["Silver"] == 0) & (df["Gold"] == 0)]

    ISO       Country  Gold  Silver  Bronze  Population  Total
0   AFG   Afghanistan     0       0       1    35320445      1
7   BHR       Bahrain     0       0       1     1323535      1
32  GRC        Greece     0       0       2    11304000      2
35  HKG     Hong Kong     0       0       1     7071600      1
48  KWT        Kuwait     0       0       1     2818042      1
51  MAR       Morocco     0       0       1    32272974      1
52  MDA       Moldova     0       0       2     3559000      2
64  QAT         Qatar     0       0       2     1870041      2
67  SAU  Saudi Arabia     0       0       1    28082541      1
68  SGP     Singapore     0       0       2     5183700      2
74  TJK    Tajikistan     0       0       1     6976958      1

## Task 3

Create a new column called "WeightedTotal", which computes a weighted total for the number of medals won by each country, with weights: Gold=3, Silver=2, Bronze=1. 

Display the top 10 countries according to this score.

In [10]:
df["WeightedTotal"] = (df["Gold"] * 3)+ (df["Silver"] * 2) + df["Bronze"]
df.sort_values("WeightedTotal", ascending=False).head(10)

,ISO,Country,Gold,Silver,Bronze,Population,Total,WeightedTotal
81,USA,United States,46,29,29,311591917,104,225
14,CHN,China,38,27,22,1344130000,87,190
66,RUS,Russian Federation,24,25,33,141930000,82,155
30,GBR,Great Britain,29,17,19,60924000,65,140
19,DEU,Germany,11,19,14,81726000,44,85
28,FRA,France,11,11,12,65436552,34,67
44,JPN,Japan,7,14,17,127817277,38,66
3,AUS,Australia,7,16,12,22620600,35,65
47,KOR,"Korea, Rep.",13,8,7,49779000,28,62
42,ITA,Italy,8,9,11,60770000,28,53

## Task 4

Create a new column "TotalPerPop" which is calculated as the total number of medals won by a country per million population.

Display the top 20 countries according to this score.

In [12]:
df["TotalPerPop"] = df["Total"] / (df["Population"] / 1_000_000)
df.sort_values("TotalPerPop", ascending=False).head(20)

,ISO,Country,Gold,Silver,Bronze,Population,Total,WeightedTotal,TotalPerPop
33,GRD,Grenada,1,0,0,104890,1,3,9.533797
43,JAM,Jamaica,4,4,4,2709300,12,24,4.429188
75,TTO,Trinidad and Tobago,1,0,3,1346350,4,6,2.970996
59,NZL,New Zealand,5,3,5,4405200,13,26,2.951058
8,BHS,Bahamas,1,0,0,347176,1,3,2.880383
71,SVN,Slovenia,1,1,2,2052000,4,7,1.949318
55,MNG,Mongolia,0,2,3,2800114,5,7,1.785642
37,HUN,Hungary,8,4,5,9971000,17,37,1.704944
20,DNK,Denmark,2,4,3,5574000,9,17,1.614639
54,MNE,Montenegro,0,1,0,632261,1,2,1.581625
49,LTU,Lithuania,2,1,2,3203000,5,10,1.561037
31,GEO,Georgia,1,3,3,4486000,7,12,1.560410
3,AUS,Australia,7,16,12,22620600,35,65,1.547262
25,EST,Estonia,0,1,1,1340000,2,3,1.492537
9,BLR,Belarus,3,5,5,9473000,13,24,1.372321
36,HRV,Croatia,3,1,2,4407000,6,13,1.361470
16,CUB,Cuba,5,3,6,11253665,14,27,1.244039
57,NLD,Netherlands,6,6,8,16696000,20,38,1.197892
40,IRL,Ireland,1,1,3,4487000,5,8,1.114330
4,AZE,Azerbaijan,2,2,6,9168000,10,16,1.090750